server:
  port: 8090
  address: 127.0.0.1
secure:
  ignored:
    urls: #安全路径白名单
      - /home/**
      - /index/**
      - /user/login
jwt:
  tokenHeader: Authorization   #请求头中存储Token的字段
  secret: java-study           #Token加解密使用的密钥
  expiration: 604800           #Token超时时限(60*60*24*7)
  tokenHead: 'Bearer '         #Token的前缀
logging:
  level:
    root: debug